package cli

import (
	"bytes"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"

	"github.com/webdeveloperben/tyche/clientgen"
)

// NewCommand builds the clientgen command under the given use name. Passing
// "clientgen" yields the standalone binary's root command; passing "client"
// yields the servergen subcommand. Both share identical flags and behavior.
func NewCommand(use string) *cobra.Command {
	var specPath, outDir, module, pkg, goVersion, clientName string

	cmd := &cobra.Command{
		Use:   use,
		Short: "Generate a self-contained typed Go client from a tyche OpenAPI spec",
		Long: "Reads an OpenAPI JSON document (e.g. the spec your tyche server emits) and\n" +
			"writes a dependency-free, typed Go client module: its own go.mod, request/\n" +
			"response types, one method per operation, and typed problem+json errors.",
		SilenceUsage:  true,
		SilenceErrors: true,
		RunE: func(cmd *cobra.Command, args []string) error {
			if specPath == "" {
				return errors.New("--spec is required")
			}
			if outDir == "" {
				return errors.New("--out is required")
			}
			if module == "" {
				return errors.New("--module is required")
			}

			data, err := os.ReadFile(specPath)
			if err != nil {
				return fmt.Errorf("read spec %q: %w", specPath, err)
			}
			doc, err := clientgen.ParseDocument(data)
			if err != nil {
				return err
			}
			res, err := clientgen.Generate(doc, clientgen.Options{
				Module:     module,
				Package:    pkg,
				GoVersion:  goVersion,
				ClientName: clientName,
			})
			if err != nil {
				return err
			}

			if err := os.MkdirAll(outDir, 0o755); err != nil {
				return fmt.Errorf("create out dir %q: %w", outDir, err)
			}
			// Remove previously generated .go files so a regeneration that drops
			// an operation (e.g. no more streaming) doesn't leave stale files
			// referencing deleted symbols.
			if err := removeGeneratedFiles(outDir); err != nil {
				return err
			}
			for _, f := range res.Files {
				dst := filepath.Join(outDir, f.Name)
				// Don't clobber a go.mod the user may have customized (a
				// module-level replace, a bumped go directive, etc.).
				if f.Name == "go.mod" {
					if _, statErr := os.Stat(dst); statErr == nil {
						continue
					}
				}
				if err := os.WriteFile(dst, f.Content, 0o644); err != nil {
					return fmt.Errorf("write %q: %w", dst, err)
				}
			}
			for _, n := range res.Notices {
				_, _ = fmt.Fprintln(cmd.ErrOrStderr(), "notice:", n)
			}
			_, _ = fmt.Fprintf(cmd.OutOrStdout(), "generated %d files into %s\n", len(res.Files), outDir)
			return nil
		},
	}

	cmd.Flags().StringVar(&specPath, "spec", "", "Path to the OpenAPI JSON document (required)")
	cmd.Flags().StringVar(&outDir, "out", "", "Output directory for the generated client module (required)")
	cmd.Flags().StringVar(&module, "module", "", "Go module path for the generated client, e.g. github.com/you/app/client (required)")
	cmd.Flags().StringVar(&pkg, "package", "", "Package name for generated files (default: derived from module)")
	cmd.Flags().StringVar(&goVersion, "go", "", "go directive for the generated go.mod (default: 1.22)")
	cmd.Flags().StringVar(&clientName, "client-name", "", "Generated client type name (default: Client)")
	return cmd
}

// generatedClientMarker is the header tyche clientgen writes on every generated
// Go file; it identifies files safe to delete on regeneration.
const generatedClientMarker = "// Code generated by tyche clientgen; DO NOT EDIT."

func removeGeneratedFiles(outDir string) error {
	entries, err := os.ReadDir(outDir)
	if err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return fmt.Errorf("read out dir %q: %w", outDir, err)
	}
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".go") {
			continue
		}
		p := filepath.Join(outDir, e.Name())
		data, err := os.ReadFile(p)
		if err != nil {
			continue
		}
		if bytes.HasPrefix(bytes.TrimSpace(data), []byte(generatedClientMarker)) {
			if err := os.Remove(p); err != nil {
				return fmt.Errorf("remove stale %q: %w", p, err)
			}
		}
	}
	return nil
}
