package clientgen

import (
	"errors"
	"fmt"
	"go/format"
	"regexp"
	"sort"
	"strings"
	"unicode"
)

// Options configures client generation.
type Options struct {
	// Module is the Go module path of the generated client (required), e.g.
	// "github.com/yourco/gateway/client". The generated go.mod uses it.
	Module string
	// Package is the package name for the generated files. Defaults to a
	// sanitized last segment of Module, or "client".
	Package string
	// GoVersion is the go directive written to go.mod. Defaults to "1.22".
	GoVersion string
	// ClientName is the generated client type name. Defaults to "Client".
	ClientName string
}

// File is a generated output file (relative path + contents).
type File struct {
	Name    string
	Content []byte
}

// Result is the output of Generate.
type Result struct {
	Files   []File
	Notices []string // non-fatal generation notes (e.g. unsupported schema features)
}

// Generate produces a self-contained, dependency-free Go client module from an
// OpenAPI document.
func Generate(doc *Document, opts Options) (*Result, error) {
	if doc == nil {
		return nil, errors.New("clientgen: nil document")
	}
	if strings.TrimSpace(opts.Module) == "" {
		return nil, errors.New("clientgen: Options.Module is required")
	}

	pkg := opts.Package
	if pkg == "" {
		pkg = packageFromModule(opts.Module)
	}
	clientName := opts.ClientName
	if clientName == "" {
		clientName = "Client"
	}
	goVersion := opts.GoVersion
	if goVersion == "" {
		goVersion = "1.22"
	}

	ts := newTypeSet(doc)
	ops := buildOperations(ts, doc)

	files := []File{
		{Name: "go.mod", Content: []byte(goModSource(opts.Module, goVersion))},
	}

	clientSrc, err := formatGo(clientRuntimeSource(pkg, clientName))
	if err != nil {
		return nil, fmt.Errorf("clientgen: format client.go: %w", err)
	}
	files = append(files, File{Name: "client.go", Content: clientSrc})

	if len(ops) > 0 {
		opsSrc, err := formatGo(operationsSource(pkg, clientName, ops))
		if err != nil {
			return nil, fmt.Errorf("clientgen: format operations.go: %w", err)
		}
		files = append(files, File{Name: "operations.go", Content: opsSrc})
	}

	if hasStreaming(ops) {
		streamSrc, err := formatGo(streamRuntimeSource(pkg, clientName))
		if err != nil {
			return nil, fmt.Errorf("clientgen: format stream.go: %w", err)
		}
		files = append(files, File{Name: "stream.go", Content: streamSrc})
	}

	typesSrc, err := formatGo(typesSource(pkg, ts))
	if err != nil {
		return nil, fmt.Errorf("clientgen: format types.go: %w", err)
	}
	files = append(files, File{Name: "types.go", Content: typesSrc})

	return &Result{Files: files, Notices: ts.notices}, nil
}

func operationsSource(pkg, clientName string, ops []*operation) string {
	var decls strings.Builder
	for _, o := range ops {
		emitInputStruct(&decls, o)
	}
	for _, o := range ops {
		emitMethod(&decls, clientName, o)
	}
	body := decls.String()

	// context and net/http are always used by method signatures and http.MethodX;
	// the rest are derived from what the generated body actually references, so a
	// file never ends up with a missing or unused import.
	imports := []string{`"context"`, `"net/http"`}
	imports = appendUsedImports(imports, body)
	return assembleFile(pkg, imports, body)
}

func typesSource(pkg string, ts *typeSet) string {
	var decls strings.Builder

	enums := append([]*enumType(nil), ts.enums...)
	sort.Slice(enums, func(i, j int) bool { return enums[i].Name < enums[j].Name })
	for _, e := range enums {
		emitEnum(&decls, e)
	}

	structs := append([]*structType(nil), ts.structs...)
	sort.Slice(structs, func(i, j int) bool { return structs[i].Name < structs[j].Name })
	for _, s := range structs {
		emitStruct(&decls, s)
	}
	body := decls.String()

	return assembleFile(pkg, appendUsedImports(nil, body), body)
}

// appendUsedImports adds stdlib imports referenced by the generated body. It
// matches the exact qualified identifiers the generator emits (never substrings
// that could appear in struct tags such as `json:"…"`), so derived imports are
// always precise.
func appendUsedImports(imports []string, body string) []string {
	if strings.Contains(body, "url.") {
		imports = append(imports, `"net/url"`)
	}
	if strings.Contains(body, "time.Time") {
		imports = append(imports, `"time"`)
	}
	if strings.Contains(body, "json.RawMessage") {
		imports = append(imports, `"encoding/json"`)
	}
	return imports
}

func assembleFile(pkg string, imports []string, body string) string {
	var b strings.Builder
	b.WriteString("// Code generated by tyche clientgen; DO NOT EDIT.\n\n")
	b.WriteString("package " + pkg + "\n\n")
	if len(imports) > 0 {
		b.WriteString("import (\n")
		for _, imp := range imports {
			b.WriteString("\t" + imp + "\n")
		}
		b.WriteString(")\n\n")
	}
	b.WriteString(body)
	return b.String()
}

func emitStruct(b *strings.Builder, s *structType) {
	if s.Doc != "" {
		fmt.Fprintf(b, "// %s: %s\n", s.Name, s.Doc)
	}
	fmt.Fprintf(b, "type %s struct {\n", s.Name)
	for _, f := range s.Fields {
		goType := f.GoType
		if f.Optional && !isNilable(goType) {
			goType = "*" + goType
		}
		tag := f.JSONName
		if f.Optional {
			tag += ",omitempty"
		}
		fmt.Fprintf(b, "\t%s %s `json:%q`\n", f.GoName, goType, tag)
	}
	b.WriteString("}\n\n")
}

func emitEnum(b *strings.Builder, e *enumType) {
	base := e.Base
	if base == "" {
		base = "string"
	}
	if e.Doc != "" {
		fmt.Fprintf(b, "// %s: %s\n", e.Name, e.Doc)
	}
	fmt.Fprintf(b, "type %s %s\n\n", e.Name, base)
	if len(e.Values) == 0 {
		return
	}
	b.WriteString("const (\n")
	constTaken := map[string]bool{}
	for _, v := range e.Values {
		if base == "string" {
			constName := uniqueName(e.Name+exportedName(v), constTaken)
			fmt.Fprintf(b, "\t%s %s = %q\n", constName, e.Name, v)
			continue
		}
		constName := uniqueName(e.Name+intEnumSuffix(v), constTaken)
		fmt.Fprintf(b, "\t%s %s = %s\n", constName, e.Name, v)
	}
	b.WriteString(")\n\n")
}

// intEnumSuffix turns an integer literal into an identifier-safe constant-name
// suffix: "3" -> "3" (valid after the enum name), "-1" -> "Neg1".
func intEnumSuffix(v string) string {
	if strings.HasPrefix(v, "-") {
		return "Neg" + v[1:]
	}
	return v
}

func isNilable(goType string) bool {
	return strings.HasPrefix(goType, "[]") ||
		strings.HasPrefix(goType, "map[") ||
		strings.HasPrefix(goType, "*") ||
		goType == "json.RawMessage" ||
		goType == "any"
}

func goModSource(module, goVersion string) string {
	return "module " + module + "\n\ngo " + goVersion + "\n"
}

var versionSuffix = regexp.MustCompile(`^v[0-9]+$`)

func packageFromModule(module string) string {
	seg := module
	if i := strings.LastIndex(module, "/"); i >= 0 {
		seg = module[i+1:]
		// Strip a major-version suffix like ".../client/v2".
		if versionSuffix.MatchString(seg) {
			if j := strings.LastIndex(module[:i], "/"); j >= 0 {
				seg = module[j+1 : i]
			} else {
				seg = module[:i]
			}
		}
	}
	var b strings.Builder
	for _, r := range strings.ToLower(seg) {
		if unicode.IsLetter(r) || unicode.IsDigit(r) {
			b.WriteRune(r)
		}
	}
	out := b.String()
	if out == "" || unicode.IsDigit(rune(out[0])) {
		return "client"
	}
	return out
}

func formatGo(src string) ([]byte, error) {
	out, err := format.Source([]byte(src))
	if err != nil {
		return nil, fmt.Errorf("%w\n--- generated source ---\n%s", err, numberedSource(src))
	}
	return out, nil
}

func numberedSource(src string) string {
	var b strings.Builder
	for i, line := range strings.Split(src, "\n") {
		fmt.Fprintf(&b, "%4d| %s\n", i+1, line)
	}
	return b.String()
}
