package clientgen

import "strings"

// clientRuntimeSource returns the static runtime portion of the generated
// client (the Client type, constructor, options, error type, and request
// plumbing). It depends only on the standard library.
func clientRuntimeSource(pkg, clientName string) string {
	body := strings.ReplaceAll(runtimeBody, "CLIENTTYPE", clientName)
	return "// Code generated by tyche clientgen; DO NOT EDIT.\n\n" +
		"package " + pkg + "\n\n" + runtimeImports + "\n" + body
}

// streamRuntimeSource returns the Server-Sent Events runtime (the generic
// Stream type and its request helper). It is emitted only when the spec
// contains at least one text/event-stream operation, so its imports are never
// unused.
func streamRuntimeSource(pkg, clientName string) string {
	body := strings.ReplaceAll(streamBody, "CLIENTTYPE", clientName)
	return "// Code generated by tyche clientgen; DO NOT EDIT.\n\n" +
		"package " + pkg + "\n\n" + streamImports + "\n" + body
}

const streamImports = `import (
	"bufio"
	"context"
	"encoding/json"
	"io"
	"net/http"
	"net/url"
	"strings"
)`

const streamBody = `
// Stream is a typed Server-Sent Events stream. Iterate it with the scanner
// pattern, and always Close it:
//
//	s, err := c.StreamThing(ctx, in)
//	if err != nil { return err }
//	defer s.Close()
//	for s.Next() {
//		ev := s.Event()
//		// ...
//	}
//	return s.Err()
type Stream[O any] struct {
	resp   *http.Response
	reader *bufio.Reader
	cur    O
	event  string
	id     string
	err    error
}

func newStream[O any](resp *http.Response) *Stream[O] {
	return &Stream[O]{resp: resp, reader: bufio.NewReader(resp.Body)}
}

// Next advances to the next event, decoding its data into the value returned by
// Event. It returns false at end of stream or on error; check Err afterwards.
func (s *Stream[O]) Next() bool {
	if s.err != nil {
		return false
	}
	var data []byte
	sawData := false
	s.event = ""
	s.id = ""
	for {
		line, err := s.reader.ReadString('\n')
		if len(line) > 0 {
			field := strings.TrimRight(line, "\r\n")
			switch {
			case field == "":
				if sawData {
					return s.decode(data)
				}
			case strings.HasPrefix(field, ":"):
				// comment / keep-alive; ignore
			default:
				name, value, _ := strings.Cut(field, ":")
				value = strings.TrimPrefix(value, " ")
				switch name {
				case "data":
					if sawData {
						data = append(data, '\n')
					}
					data = append(data, value...)
					sawData = true
				case "event":
					s.event = value
				case "id":
					s.id = value
				}
			}
		}
		if err != nil {
			if err == io.EOF {
				if sawData {
					return s.decode(data)
				}
				return false
			}
			s.err = err
			return false
		}
	}
}

func (s *Stream[O]) decode(data []byte) bool {
	var v O
	if err := json.Unmarshal(data, &v); err != nil {
		s.err = err
		return false
	}
	s.cur = v
	return true
}

// Event returns the value decoded by the most recent call to Next.
func (s *Stream[O]) Event() O { return s.cur }

// EventName returns the SSE "event" field of the most recent event, if any.
func (s *Stream[O]) EventName() string { return s.event }

// ID returns the SSE "id" field of the most recent event, if any.
func (s *Stream[O]) ID() string { return s.id }

// Err returns the first non-EOF error encountered while streaming.
func (s *Stream[O]) Err() error { return s.err }

// Header returns the response headers of the stream.
func (s *Stream[O]) Header() http.Header { return s.resp.Header }

// Response returns the underlying HTTP response. Do not read its Body directly;
// iterate the stream instead.
func (s *Stream[O]) Response() *http.Response { return s.resp }

// Close releases the underlying response body.
func (s *Stream[O]) Close() error { return s.resp.Body.Close() }

func doStream[O any](ctx context.Context, c *CLIENTTYPE, method, path string, query url.Values, header http.Header, body any, opts []CallOption) (*Stream[O], error) {
	co := resolveCallOptions(opts)
	header = mergeHeaders(header, co.header)
	if header == nil {
		header = http.Header{}
	}
	if header.Get("Accept") == "" {
		header.Set("Accept", "text/event-stream")
	}
	resp, err := c.send(ctx, method, path, query, header, body)
	if err != nil {
		return nil, err
	}
	for _, fn := range co.onResponse {
		fn(resp)
	}
	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		data, _ := io.ReadAll(resp.Body)
		_ = resp.Body.Close()
		return nil, parseAPIError(resp.StatusCode, data)
	}
	return newStream[O](resp), nil
}
`

const runtimeImports = `import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strconv"
	"strings"
	"time"
)`

const runtimeBody = `
// CLIENTTYPE is a typed client for the API.
type CLIENTTYPE struct {
	baseURL    string
	httpClient *http.Client
	header     http.Header
}

// Option configures a CLIENTTYPE.
type Option func(*CLIENTTYPE)

// New returns a CLIENTTYPE that targets baseURL.
func New(baseURL string, opts ...Option) *CLIENTTYPE {
	c := &CLIENTTYPE{
		baseURL:    strings.TrimRight(baseURL, "/"),
		httpClient: http.DefaultClient,
		header:     http.Header{},
	}
	for _, o := range opts {
		o(c)
	}
	return c
}

// WithHTTPClient sets the underlying *http.Client used for requests.
func WithHTTPClient(h *http.Client) Option {
	return func(c *CLIENTTYPE) {
		if h != nil {
			c.httpClient = h
		}
	}
}

// WithBearerToken sets a default "Authorization: Bearer <token>" header.
func WithBearerToken(token string) Option {
	return func(c *CLIENTTYPE) { c.header.Set("Authorization", "Bearer "+token) }
}

// WithHeader sets a default header sent on every request.
func WithHeader(key, value string) Option {
	return func(c *CLIENTTYPE) { c.header.Set(key, value) }
}

// ProblemError is a single field-level validation problem from an error response.
type ProblemError struct {
	Pointer string ` + "`json:\"pointer\"`" + `
	Code    string ` + "`json:\"code\"`" + `
	Message string ` + "`json:\"message\"`" + `
}

// APIError is returned for any non-2xx response, decoded from the RFC 9457
// application/problem+json body when present.
type APIError struct {
	StatusCode int            ` + "`json:\"-\"`" + `
	Type       string         ` + "`json:\"type\"`" + `
	Title      string         ` + "`json:\"title\"`" + `
	Status     int            ` + "`json:\"status\"`" + `
	Detail     string         ` + "`json:\"detail\"`" + `
	Errors     []ProblemError ` + "`json:\"errors\"`" + `
	Body       []byte         ` + "`json:\"-\"`" + `
}

func (e *APIError) Error() string {
	switch {
	case e.Detail != "":
		return fmt.Sprintf("api error %d: %s: %s", e.StatusCode, e.Title, e.Detail)
	case e.Title != "":
		return fmt.Sprintf("api error %d: %s", e.StatusCode, e.Title)
	default:
		return fmt.Sprintf("api error %d", e.StatusCode)
	}
}

func (c *CLIENTTYPE) applyHeaders(req *http.Request, header http.Header) {
	for k, vs := range c.header {
		req.Header[http.CanonicalHeaderKey(k)] = append([]string(nil), vs...)
	}
	for k, vs := range header {
		req.Header[http.CanonicalHeaderKey(k)] = append([]string(nil), vs...)
	}
}

// send builds and dispatches a request, returning the response with its body
// still open. Callers are responsible for closing resp.Body.
func (c *CLIENTTYPE) send(ctx context.Context, method, path string, query url.Values, header http.Header, body any) (*http.Response, error) {
	u := c.baseURL + path
	if len(query) > 0 {
		u += "?" + query.Encode()
	}
	var reader io.Reader
	if body != nil {
		buf, err := json.Marshal(body)
		if err != nil {
			return nil, fmt.Errorf("encode request body: %w", err)
		}
		reader = bytes.NewReader(buf)
	}
	req, err := http.NewRequestWithContext(ctx, method, u, reader)
	if err != nil {
		return nil, err
	}
	c.applyHeaders(req, header)
	if body != nil {
		req.Header.Set("Content-Type", "application/json")
	}
	if req.Header.Get("Accept") == "" {
		req.Header.Set("Accept", "application/json")
	}
	return c.httpClient.Do(req)
}

// CallOption customizes a single request.
type CallOption func(*callOptions)

type callOptions struct {
	header     http.Header
	onResponse []func(*http.Response)
}

// WithRequestHeader adds a header to a single request, in addition to the
// client's default headers.
func WithRequestHeader(key, value string) CallOption {
	return func(o *callOptions) {
		if o.header == nil {
			o.header = http.Header{}
		}
		o.header.Add(key, value)
	}
}

// WithResponseCallback registers a function invoked with the raw *http.Response,
// giving access to the status and response headers. For non-streaming calls the
// body has already been read and closed by the time it runs, so read only
// headers/status there; for streaming calls it runs before iteration begins and
// the body must not be consumed.
func WithResponseCallback(fn func(*http.Response)) CallOption {
	return func(o *callOptions) { o.onResponse = append(o.onResponse, fn) }
}

func resolveCallOptions(opts []CallOption) callOptions {
	var c callOptions
	for _, o := range opts {
		o(&c)
	}
	return c
}

func mergeHeaders(base, extra http.Header) http.Header {
	if len(extra) == 0 {
		return base
	}
	merged := http.Header{}
	for k, vs := range base {
		merged[k] = append([]string(nil), vs...)
	}
	for k, vs := range extra {
		for _, v := range vs {
			merged.Add(k, v)
		}
	}
	return merged
}

func (c *CLIENTTYPE) do(ctx context.Context, method, path string, query url.Values, header http.Header, body any, opts []CallOption) (*http.Response, []byte, error) {
	co := resolveCallOptions(opts)
	resp, err := c.send(ctx, method, path, query, mergeHeaders(header, co.header), body)
	if err != nil {
		return nil, nil, err
	}
	defer resp.Body.Close()
	out, readErr := io.ReadAll(resp.Body)
	for _, fn := range co.onResponse {
		fn(resp)
	}
	if readErr != nil {
		return resp, nil, fmt.Errorf("read response body: %w", readErr)
	}
	return resp, out, nil
}

func parseAPIError(status int, body []byte) *APIError {
	e := &APIError{StatusCode: status, Body: body}
	if len(body) > 0 {
		_ = json.Unmarshal(body, e)
	}
	return e
}

func doJSON[O any](ctx context.Context, c *CLIENTTYPE, method, path string, query url.Values, header http.Header, body any, opts []CallOption) (*O, error) {
	resp, data, err := c.do(ctx, method, path, query, header, body, opts)
	if err != nil {
		return nil, err
	}
	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		return nil, parseAPIError(resp.StatusCode, data)
	}
	var env struct {
		Data O ` + "`json:\"data\"`" + `
	}
	if len(data) > 0 {
		if err := json.Unmarshal(data, &env); err != nil {
			return nil, fmt.Errorf("decode response: %w", err)
		}
	}
	return &env.Data, nil
}

func doDiscard(ctx context.Context, c *CLIENTTYPE, method, path string, query url.Values, header http.Header, body any, opts []CallOption) error {
	resp, data, err := c.do(ctx, method, path, query, header, body, opts)
	if err != nil {
		return err
	}
	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		return parseAPIError(resp.StatusCode, data)
	}
	return nil
}

// fmtParam renders a path/query/header value as a string.
func fmtParam(v any) string {
	switch t := v.(type) {
	case string:
		return t
	case time.Time:
		return t.Format(time.RFC3339)
	case bool:
		return strconv.FormatBool(t)
	case int:
		return strconv.FormatInt(int64(t), 10)
	case int32:
		return strconv.FormatInt(int64(t), 10)
	case int64:
		return strconv.FormatInt(t, 10)
	case float32:
		return strconv.FormatFloat(float64(t), 'g', -1, 32)
	case float64:
		return strconv.FormatFloat(t, 'g', -1, 64)
	case fmt.Stringer:
		return t.String()
	default:
		return fmt.Sprint(v)
	}
}
`
